'use strict';
const $=id=>document.getElementById(id), SCHEMA='human-review-v1';
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let data,state,session,currentId,visible=[],dirty=false,timer=null,busy=Promise.resolve(),lastError=null;
const labels={valid:'תקין',ambiguous:'עמום',suspect_gold:'תווית ייחוס חשודה',missing_candidate:'מועמד מתאים חסר',target_occurrence:'בעיית הופעת מטרה',other:'אחר'};
const quality={correct:'נכונה במשמעות',wrong:'שגויה במשמעות',partial:'חלקית / לא ניתנת להכרעה',no_answer:'אין תשובה'};
const record=()=>state.records[currentId]||{exposure:{}};
const item=()=>data.items.find(i=>i.id===currentId);
const system=id=>data.systems.find(s=>s.id===id)||{blind_id:id,name:id};
const select=(id,values,value='')=>`<select id="${id}"><option value="">טרם סומן</option>${Object.entries(values).map(([k,v])=>`<option value="${esc(k)}" ${k===value?'selected':''}>${esc(v)}</option>`).join('')}</select>`;
const check=(id,text,checked)=>`<label class="check"><input type="checkbox" id="${id}" ${checked?'checked':''}>${text}</label>`;
function status(text,error=false){$('saveStatus').textContent=text;$('saveStatus').className=error?'error':'';}
async function request(path,body){const response=await fetch(path,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{});const result=await response.json();if(!response.ok)throw new Error(result.error||response.statusText);return result;}
function serialize(fn){const task=busy.then(fn);busy=task.catch(()=>{});return task;}
function annotationFromForm(){
 const i=item(),old=record().draft||record().reviewed||{};
 if(!i)return null;
 const a={...old,schema_version:SCHEMA,annotator:$('annotator').value.trim(),interpretation:$('interpretation').value,interpretation_kind:$('interpretationKind').value,prior_exposure:$('priorExposure').value,item_problems:[...document.querySelectorAll('[data-problem]:checked')].map(e=>e.dataset.problem),confidence:$('confidence').value,note:$('note').value,revisit:$('revisit').checked,example:$('example').checked,answers:{...(old.answers||{})}};
 for(const answer of i.answers){if($(`quality-${answer.id}`))a.answers[answer.id]={...(a.answers[answer.id]||{}),system_id:answer.system_id,quality:$(`quality-${answer.id}`).value,format_ok:$(`format-${answer.id}`).value,disagrees_auto:$(`disagree-${answer.id}`).value,confidence:$(`confidence-${answer.id}`).value,note:$(`note-${answer.id}`).value};}
 return a;
}
function markDirty(){dirty=true;lastError=null;clearTimeout(timer);status('שינויים ממתינים לשמירה…');timer=setTimeout(()=>save('draft').catch(showError),650);}
function showError(e){lastError=e;status('לא נשמר: '+e.message+' · השאירו את החלון פתוח ונסו שוב.',true);}
async function save(action='draft'){
 clearTimeout(timer);
 if(!item()||(!dirty&&action==='draft'))return;
 const id=currentId,annotation=annotationFromForm();
 if(!annotation.annotator){const e=new Error('מלאו זהות מתייג/ת כדי לשמור את העבודה');showError(e);throw e;}
 status('שומר בדיסק…');
 const snapshot=JSON.stringify(annotation);
 await serialize(async()=>{state=await request('/api/update',{revision:state.revision,item_id:id,action,annotation});});
 if(currentId===id&&JSON.stringify(annotationFromForm())===snapshot){dirty=false;}else if(currentId===id){
 // updated_at is added by the server; it is not an unsaved form edit.
 const current=annotationFromForm();delete current.updated_at;const submitted={...annotation};delete submitted.updated_at;dirty=JSON.stringify(current)!==JSON.stringify(submitted);
 }
 lastError=null;status(`${action==='review'?'נשמר כבדוק':'טיוטה נשמרה'} בדיסק · ${new Date(state.saved_at).toLocaleTimeString('he-IL')}`);
 renderSummary();
 if(action==='review'&&!dirty)render();
}
let lockDepth=0;
async function locked(fn){lockDepth++;document.querySelector('main').inert=true;document.querySelector('header').inert=true;try{return await fn();}finally{lockDepth--;if(!lockDepth){document.querySelector('main').inert=false;document.querySelector('header').inert=false;}}}
async function flush(){while(dirty)await save('draft');}
async function expose(stage){return locked(async()=>{try{await flush();await serialize(async()=>{state=await request('/api/update',{revision:state.revision,item_id:currentId,action:'expose',stage});});status('החשיפה תועדה בדיסק · '+new Date(state.saved_at).toLocaleTimeString('he-IL'));render();}catch(e){showError(e);}});}
function baseQueue(){return $('queue').value==='all'?data.items.map(i=>i.id):(data.queues[$('queue').value]||[]);}
function filtered(){const ids=new Set(baseQueue());return data.items.filter(i=>{
 if(!ids.has(i.id)||($('sourceFilter').value&&String(i.source)!==$ ('sourceFilter').value)||($('acronymFilter').value&&i.acronym!==$('acronymFilter').value))return false;
 const r=state.records[i.id]||{},a=r.draft||r.reviewed||{};const answers=Object.values(a.answers||{}),s=$('statusFilter').value,f=$('findingFilter').value;
 if($('systemFilter').value&&!i.answers.some(x=>x.system_id===$('systemFilter').value))return false;
 if(s==='new'&&(r.draft||r.reviewed))return false;if(s==='draft'&&(!r.draft||JSON.stringify(r.draft)===JSON.stringify(r.reviewed)))return false;if(s==='reviewed'&&!r.reviewed)return false;if((s==='revisit'||s==='example')&&!a[s])return false;
 if(f==='mechanical'&&!(i.findings||[]).length)return false;if(f==='disagreement'&&!answers.some(x=>x.disagrees_auto==='yes'))return false;if(['wrong','partial'].includes(f)&&!answers.some(x=>x.quality===f))return false;if(f&&!['mechanical','disagreement','wrong','partial'].includes(f)&&!(a.item_problems||[]).includes(f))return false;
 return true;
 }).map(i=>i.id).sort((a,b)=>baseQueue().indexOf(a)-baseQueue().indexOf(b));}
async function navigate(id){return locked(async()=>{try{await flush();currentId=id;render();}catch(e){showError(e);}});}
function refreshList(){visible=filtered();if(!visible.includes(currentId))currentId=visible[0];render();}
function renderSummary(){const ids=new Set(baseQueue()),reviews=Object.entries(state.records).filter(([id,r])=>ids.has(id)&&r.reviewed).map(([,r])=>r.reviewed);const judgments=reviews.flatMap(r=>Object.values(r.answers||{})).filter(a=>a.quality);const possible=baseQueue().reduce((n,id)=>n+(data.items.find(i=>i.id===id)?.answers.length||0),0);$('summary').innerHTML=`<div class="summary-line"><strong>${reviews.length}</strong> פריטים בדוקים מתוך ${ids.size} במסלול</div><div class="summary-line"><strong>${judgments.length}</strong> תשובות עם שיפוט מתוך ${possible} במסלול</div>${Object.entries(quality).map(([k,v])=>`<div class="hint">${v}: ${judgments.filter(j=>j.quality===k).length} / ${judgments.length} תשובות מתויגות</div>`).join('')}`;}
function remember(){if(!data)return;const preferences={currentId,annotator:$('annotator').value,filters:{}};for(const id of ['queue','sourceFilter','acronymFilter','systemFilter','findingFilter','statusFilter'])preferences.filters[id]=$(id).value;try{localStorage.setItem('human-review-ui-'+data.dataset_id,JSON.stringify(preferences));}catch(_){} }
function render(){
 remember();
 const i=item();$('position').textContent=visible.length?`${visible.indexOf(currentId)+1} / ${visible.length}`:'אין התאמות';$('jump').innerHTML=visible.map(id=>`<option ${id===currentId?'selected':''} value="${esc(id)}">${esc(id)}</option>`).join('');$('previous').disabled=visible.indexOf(currentId)<=0;$('next').disabled=visible.indexOf(currentId)>=visible.length-1;
 const queue=$('queue').value;$('queueNote').textContent=queue==='calibration'?'כיול ההגדרות והממשק; הבחירה קבועה וניתנת לשחזור.':queue==='diagnosis'?'תור מועשר בדגלים מכניים ושגיאות בניקוד המקורי. אין להכליל ממנו שיעורי שגיאות.':queue==='evaluation'?'מדגם קבוע ומאוזן בקבוצות מקור וסוג. הצלחות אוטומטיות נכללות; אין זה מדגם יחסי.':'כל מאגר הבדיקה. אין לייחס סדר זה לדגימה אקראית.';
 renderSummary();if(!i){$('itemView').innerHTML='<div class="empty">אין פריטים התואמים למסננים.</div>';$('saveReview').disabled=true;$('saveNext').disabled=true;return;}$('saveReview').disabled=false;$('saveNext').disabled=false;
 const r=record(),a=r.draft||r.reviewed||{},e=r.exposure||{},problems=a.item_problems||[];
 let highlighted='',cursor=0;for(const span of (i.target_spans||[])){if(span.start>=cursor&&span.end<=i.sentence.length){highlighted+=esc(i.sentence.slice(cursor,span.start))+'<mark>'+esc(i.sentence.slice(span.start,span.end))+'</mark>';cursor=span.end;}}highlighted+=esc(i.sentence.slice(cursor));
 $('itemView').innerHTML=`<article class="card"><div class="meta"><span class="pill"><bdi>${esc(i.id)}</bdi></span><span class="pill">מקור: ${esc(i.source)}</span><span class="pill">${esc(i.origin||'מקור לא מתועד')}</span><span class="pill">קיצור: ${esc(i.acronym)}</span><span class="pill">${r.reviewed?'נשמר כבדוק':r.draft?'טיוטה':'טרם תויג'}</span></div><div class="sentence">${highlighted}</div><p class="hint">ההדגשה היא התאמת טקסט מכנית לקיצור בלבד. אינה סימון מוסמך של הופעת המטרה; ייתכנו כמה הופעות או התאמות חסרות.</p><details><summary>זהות הפריט וסיבת הכניסה לתור</summary><pre>${esc(JSON.stringify({selection_reasons:e.auto_scores?i.selection_reasons:'סיבת הבחירה המפורטת זמינה לאחר חשיפת ניקוד; עשויה לרמוז לתשובות',category:i.source_metadata?.category,page_title:i.source_metadata?.page_title,acronym_type_proxy:i.acronym_type_proxy,prior_exposure:i.prior_exposure},null,2))}</pre></details>${Object.keys(e).length?`<div class="exposure">כבר נחשפו בפריט זה: ${Object.keys(e).map(k=>({candidates:'מועמדים',gold:'ייחוס',responses:'תשובות',identities:'שמות מערכות',auto_scores:'ניקוד אוטומטי'}[k])).join(' · ')}. חזרה לפריט אינה משחזרת עיוורון.</div>`:''}</article>
 <section class="card"><div class="step">שלב א · ניסיון עצמאי</div><h2>מה פירוש הקיצור בהקשר?</h2><label for="interpretation">פרשנות קצרה או כמה אפשרויות</label><textarea id="interpretation" placeholder="אפשר לכתוב בקצרה; אין צורך בהסבר ארוך">${esc(a.interpretation||'')}</textarea><div class="row"><div><label for="interpretationKind">מצב הפרשנות</label>${select('interpretationKind',{interpretation:'יש לי פרשנות',multiple:'כמה אפשרויות',no_context:'אין די הקשר',needs_check:'נדרשת בדיקה'},a.interpretation_kind)}</div><div><label for="priorExposure">האם ראית את הפריט או תשובותיו קודם?</label><select id="priorExposure"><option value="unknown" ${(a.prior_exposure||i.prior_exposure||'unknown')==='unknown'?'selected':''}>לא ידוע</option><option value="yes" ${a.prior_exposure==='yes'?'selected':''}>כן</option><option value="no" ${a.prior_exposure==='no'?'selected':''}>לא, ככל הידוע לי</option></select></div></div>
 ${!e.candidates?'<div class="reveal"><p>לאחר הניסיון הראשוני אפשר להיעזר ברשימת המועמדים. החשיפה נשמרת גם לאחר סגירת החלון.</p><button data-expose="candidates">חשיפת מועמדים</button></div>':`<div class="reveal"><strong>מועמדים בקובץ המקור (אינם בהכרח סדר האותיות)</strong><p>${(i.candidates||[]).map(esc).join(' · ')||'לא זמין'}</p><p class="hint">חשיפה ראשונה: <bdi>${esc(e.candidates)}</bdi></p>${!e.gold?'<button data-expose="gold">חשיפת תווית הייחוס</button>':`<strong>תווית הייחוס: ${esc(i.gold??'לא זמינה')}</strong><p class="hint">תווית מקור, לא שיפוט אנושי מאומת.</p>`}</div>`}</section>
 ${e.gold?`<section class="card"><div class="step">שלב ב · איכות הפריט והייחוס</div><h2>אפשר לסמן כמה בעיות</h2><div class="checks">${Object.entries(labels).map(([k,v])=>`<label class="check"><input type="checkbox" data-problem="${k}" ${problems.includes(k)?'checked':''}>${v}</label>`).join('')}</div><p class="hint">״תקין״ עומד בפני עצמו. תווית חשודה אינה תיקון אוטומטי של הייחוס.</p>${!e.responses?'<div class="reveal"><button data-expose="responses">חשיפת תשובות המערכות</button></div>':''}</section>`:''}
 ${e.responses?`<section class="card"><div class="section-title"><div><div class="step">שלב ב · איכות התשובות</div><h2>שיפוט משמעות לכל תשובה בנפרד</h2></div><span class="pill">${i.answers.length} תשובות</span></div><p class="hint">קודי המערכות קבועים. תוכן התשובות עשוי לרמוז לזהותן; אין כאן טענה לעיוורון מלא. פורמט ומשמעות הם צירים נפרדים.</p>${i.answers.filter(answer=>!$('systemFilter').value||answer.system_id===$('systemFilter').value).map(answer=>answerHTML(answer,a.answers?.[answer.id]||{},e)).join('')}<div class="reveal">${e.identities?'<strong>שמות המערכות נחשפו ונרשמו</strong>':`<button data-expose="identities" ${!r.reviewed||JSON.stringify(r.draft)!==JSON.stringify(r.reviewed)?'disabled':''}>חשיפת שמות לאחר שמירה מפורשת</button>`}<p class="hint">לחשיפת שמות יש לשמור את השינויים כבדוקים תחילה. החשיפה בלתי הפיכה בהיסטוריית הפריט.</p>${!e.auto_scores?'<button data-expose="auto_scores">חשיפת הניקוד האוטומטי והדגלים המכניים</button>':''}</div>${e.auto_scores?`<div class="warning">ממצאים מכניים: ${esc((i.findings||[]).join(' · ')||'אין דגלים')}<p>דגלים אלה אינם תיוגים סמנטיים.</p></div>`:''}</section>`:''}
 <section class="card"><h2>ביטחון והמשך</h2><div class="row"><div><label for="confidence">ביטחון בשיפוט הפריט</label>${select('confidence',{high:'גבוה',medium:'בינוני',low:'נמוך'},a.confidence)}</div><div class="checks">${check('revisit','לחזור לפריט',a.revisit)}${check('example','דוגמה אפשרית למאמר',a.example)}</div></div><label for="note">הערה אופציונלית</label><textarea id="note" placeholder="הסבר קצר, צורך בבדיקה או משוב לכיול">${esc(a.note||'')}</textarea>${r.reviewed?`<p class="hint">בדיקה מפורשת אחרונה: <bdi>${esc(r.reviewed_at||r.reviewed.updated_at)}</bdi> · מתייג/ת: ${esc(r.reviewed.annotator)}. עריכה חדשה נשמרת כטיוטה עד שמירה מפורשת נוספת.</p>`:''}</section>`;
 // Item labels exist only after gold reveal; retain earlier blank state safely.
 $('itemView').querySelectorAll('input,select,textarea').forEach(el=>el.addEventListener('input',()=>{if(el.dataset.problem==='valid'&&el.checked)document.querySelectorAll('[data-problem]').forEach(other=>{if(other!==el)other.checked=false;});else if(el.dataset.problem&&el.checked){const valid=document.querySelector('[data-problem="valid"]');if(valid)valid.checked=false;}markDirty();}));
 $('itemView').querySelectorAll('[data-expose]').forEach(el=>el.addEventListener('click',()=>expose(el.dataset.expose)));
}
function answerHTML(answer,j,e){const sys=system(answer.system_id),mapping=answer.option_mapping||[];return `<div class="answer"><h3><bdi>${esc(sys.blind_id||sys.pseudonym||sys.id)}</bdi>${e.identities?' · <bdi>'+esc(sys.name||sys.id)+'</bdi>':''} <span class="hint">${answer.task==='selection'?'בחירה במועמדים':'יצירה חופשית'}</span></h3><label>טקסט התשובה הגולמי</label><div class="raw" dir="auto">${esc(answer.raw??'אין תשובה זמינה')}</div>${answer.missing?'<div class="warning">תשובה חסרה במקור. אין תיוג אנושי אוטומטי.</div>':''}<p>פענוח מכני: <strong>${esc(answer.decoded??'לא זמין / לא פוענח')}</strong></p>${mapping.length?`<details><summary>סדר המועמדים שהוצג בפועל ומיפוי אותיות</summary>${mapping.map(x=>`<div><bdi>${esc(x.letter)}</bdi> — ${esc(x.candidate)}</div>`).join('')}${answer.mapping_note?`<p class="warning">${esc(answer.mapping_note)}</p>`:''}${answer.omitted_candidates?.length?`<p class="warning">מועמדים שמורים שלא הוצגו בפרומפט: ${answer.omitted_candidates.map(esc).join(' · ')}</p>`:''}${answer.shown_order?`<details><summary>סדר שמור מלא (עשוי להיות ארוך מההצגה בפועל)</summary><pre>${esc(JSON.stringify(answer.shown_order,null,2))}</pre></details>`:''}</details>`:''}<div class="row"><div><label for="quality-${esc(answer.id)}">איכות התשובה במשמעות</label>${select('quality-'+answer.id,quality,j.quality)}</div><div><label for="format-${esc(answer.id)}">עמידה בפורמט הנדרש</label>${select('format-'+answer.id,{yes:'כן',no:'לא',unknown:'לא ניתן לקבוע'},j.format_ok)}</div><div><label for="disagree-${esc(answer.id)}">פער מול הניקוד האוטומטי</label>${select('disagree-'+answer.id,{yes:'יש פער',no:'אין פער',unknown:'טרם נבדק / לא ניתן לקבוע'},j.disagrees_auto)}</div><div><label for="confidence-${esc(answer.id)}">ביטחון בתשובה זו</label>${select('confidence-'+answer.id,{high:'גבוה',medium:'בינוני',low:'נמוך'},j.confidence)}</div></div><label for="note-${esc(answer.id)}">הערה לתשובה (אופציונלי)</label><textarea id="note-${esc(answer.id)}">${esc(j.note||'')}</textarea>${e.auto_scores?`<details><summary>ניקוד אוטומטי מקורי ופרטי המקור</summary><pre>${esc(JSON.stringify({answer_id:e.identities?answer.id:undefined,original_auto_score:answer.auto_score,auto_score_rule:answer.auto_score_rule,original_valid:answer.auto_valid,mechanical_flags:answer.mechanical_flags,source:e.identities?answer.source_file:undefined},null,2))}</pre><p class="hint">הדגל המקורי valid אינו בהכרח בדיקת פורמט. הוא אינו ממלא את השיפוט שלך.</p></details>`:''}</div>`;}
async function init(){try{[data,state,session]=await Promise.all([request('/api/data'),request('/api/state'),request('/api/session')]);if(session.qa){const banner=document.createElement('div');banner.className='warning';banner.textContent='סביבת בדיקת תוכנה בלבד (QA) · כל התיוגים כאן נפרדים מעבודת המחקר';document.body.prepend(banner);}
 for(const [id,values]of [['sourceFilter',[...new Set(data.items.map(i=>String(i.source)))]],['acronymFilter',[...new Set(data.items.map(i=>i.acronym))]]])$(id).innerHTML='<option value="">הכול</option>'+values.sort((a,b)=>a.localeCompare(b,'he')).map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('');
 $('systemFilter').innerHTML='<option value="">כל המערכות</option>'+data.systems.map(s=>`<option value="${esc(s.id)}">${esc(s.blind_id||s.pseudonym||s.id)}</option>`).join('');$('provenance').textContent=JSON.stringify({dataset_id:data.dataset_id,...data.provenance},null,2);
 try{const preferences=JSON.parse(localStorage.getItem('human-review-ui-'+data.dataset_id)||'{}');currentId=preferences.currentId;$('annotator').value=preferences.annotator||'';for(const [id,value]of Object.entries(preferences.filters||{})){if($(id)&&[...$(id).options].some(o=>o.value===value))$(id).value=value;}}catch(_){}
 for(const id of ['queue','sourceFilter','acronymFilter','systemFilter','findingFilter','statusFilter'])$(id).addEventListener('change',()=>locked(async()=>{try{await flush();refreshList();}catch(e){showError(e);}}));
 $('clearFilters').onclick=()=>locked(async()=>{try{await flush();for(const id of ['sourceFilter','acronymFilter','systemFilter','findingFilter','statusFilter'])$(id).value='';refreshList();}catch(e){showError(e);}});
 $('annotator').addEventListener('change',()=>{remember();if(record().draft||record().reviewed)markDirty();});
 $('previous').onclick=()=>navigate(visible[visible.indexOf(currentId)-1]);$('next').onclick=()=>navigate(visible[visible.indexOf(currentId)+1]);$('jump').onchange=()=>navigate($('jump').value);$('saveReview').onclick=()=>locked(()=>save('review')).catch(showError);$('saveNext').onclick=()=>locked(async()=>{try{await save('review');const next=visible[visible.indexOf(currentId)+1];if(next)await navigate(next);else status('המסלול הנוכחי הושלם. זה הזמן למשוב על הכיול.');}catch(e){showError(e);}});
 $('importButton').onclick=()=>locked(async()=>{const file=$('importFile').files[0];if(!file)return;try{await flush();if(!confirm('הייבוא יחליף את התיוגים של פריטים תואמים בקובץ. יישמר תיעוד בהיסטוריה. להמשיך?'))return;const text=await file.text();await serialize(async()=>{state=await request('/api/import',{revision:state.revision,format:file.name.endsWith('.csv')?'csv':'json',text});});dirty=false;status('הייבוא נשמר בדיסק');refreshList();}catch(e){showError(e);}});
 window.addEventListener('beforeunload',event=>{if(dirty||lastError){event.preventDefault();event.returnValue='';}});refreshList();status(state.saved_at?'נטען מהדיסק · '+new Date(state.saved_at).toLocaleString('he-IL'):'מוכן · עדיין אין תיוגים שמורים');
 }catch(e){showError(e);}finally{document.querySelector('main').inert=false;document.querySelector('header').inert=false;}}
init();
